In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("ecommerce_sales_raw.xlsx")

In [3]:
df.head()

,order_id,Name,gender,DOB,email,phone,country,city,region,pincode,...,interest,product_category,product_name,quantity,unit_price,discount,order_date,payment_mode,order_status,revenue
0,ORD11749,James Landry,MALE,07-19-2003,parksandre@example.com,+1-832-526-5278x254,United Kingdom,West Christineland,East,97210.0,...,Reading,Clothing,Formal Shirt,5,247.49,0.20,2023-09-14,COD,Delivered,989.96
1,ORD12802,Lisa Scott,Male,12-Aug-1966,whitney14@example.org,563.525.5861,USA,Lake Jason,South,46086.0,...,Travel,Sports,Dumbbell Set,2,430.16,0.00,2023-11-09,upi,Returned,860.32
2,ORD11421,Kristen Young,m,12-28-1980,NaN,NaN,canada,Josephshire,East,46690.0,...,Sports,Electronics,USB-C Hub,1,75.43,1.50,22/01/2023,Debit Card,Cancelled,-37.72
3,ORD10227,stephanie khan,FEMALE,NaN,heather21@example.org,875-818-6892,INDIA,Port Georgemouth,North,74621.0,...,Travel,Home & Kitchen,Non-stick Pan,5,98.99,1.50,28/09/2024,Debit Card,returned,-247.47
4,ORD10592,jeanne hernandez,f,NaN,perezcourtney@example.com,+1-270-371-3984x82285,India,South Apriltown,South,81580.0,...,Music,Electronics,Wireless Mouse,2,433.84,0.15,06-09-2024,UPI,Cancelled,737.53

In [4]:
df.tail()

,order_id,Name,gender,DOB,email,phone,country,city,region,pincode,...,interest,product_category,product_name,quantity,unit_price,discount,order_date,payment_mode,order_status,revenue
3105,ORD10969,DAVID JONES,f,12-28-1995,andrewsjohn@example.org,NaN,NaN,East Ethan,North,61276.0,...,Music,Beauty,Lipstick Set,5,310.43,0.10,10/03/2023,COD,returned,1396.94
3106,ORD11958,Janice Lee,FEMALE,16-Oct-1997,robertwatson@example.org,NaN,U.S.A,Port Crystal,North,80192.0,...,Gaming,Sports,Cricket Bat,5,160.18,0.15,2024-05-29,upi,cancelled,680.77
3107,ORD11668,Teresa Little,m,12-01-1979,colonjames@example.org,927-616-1862x869,Canada,Butlerburgh,West,28760.0,...,Travel,Sports,Cricket Bat,2,38.20,0.05,06-Apr-2024,debit card,cancelled,72.58
3108,ORD11689,sara hobbs,F,NaN,NaN,NaN,India,North Christopherfort,West,94847.0,...,Reading,Sports,Cricket Bat,-1,466.25,0.20,08-11-2023,debit card,Shipped,-373.00
3109,ORD11899,SARA RAMIREZ,NaN,03-06-2007,eoneal@example.org,+1-605-985-8240,U.S.A,Dawsonshire,South,92543.0,...,Travel,Home & Kitchen,LED Lamp,2,229.99,0.00,2023-08-24,COD,shipped,459.98

In [5]:
df.describe()

            pincode     quantity   unit_price     discount      revenue
count   2357.000000  3110.000000  3110.000000  3110.000000  2936.000000
mean   49380.900721     1.743408   253.586839     0.227605   332.449991
std    28896.767295     1.652823   144.327614     0.472513   525.389687
min      579.000000    -1.000000     5.030000    -0.100000 -1166.120000
25%    24036.000000     1.000000   126.505000     0.000000    28.365000
50%    48852.000000     1.000000   253.530000     0.100000   246.110000
75%    74743.000000     2.000000   378.367500     0.150000   524.597500
max    99945.000000     5.000000   499.940000     1.500000  2455.050000

In [6]:
df.sample(5)

,order_id,Name,gender,DOB,email,phone,country,city,region,pincode,...,interest,product_category,product_name,quantity,unit_price,discount,order_date,payment_mode,order_status,revenue
843,ORD12576,Kyle Evans,M,09/05/1999,ana77@example.org,(339)728-3109,United States,Durhamland,West,1890.0,...,NaN,Sports,Dumbbell Set,-1,408.03,0.00,02-Aug-2023,cash on delivery,shipped,-408.03
2560,ORD12354,deanna williams,Male,1985-05-09,NaN,486-483-0434,India,Fernandezborough,South,17642.0,...,Sports,Books,Self-Help Book,2,53.17,0.05,08-26-2024,debit card,delivered,NaN
58,ORD10801,Michael Cross DDS,MALE,NaN,NaN,NaN,india,North Stephanie,North,NaN,...,Sports,Books,Kids Story Book,2,54.69,-0.10,12-28-2024,upi,Cancelled,109.38
2725,ORD10010,Krista Williams,f,25-Jul-2008,novaksara@example.org,NaN,NaN,South Todd,North,NaN,...,Sports,Electronics,Bluetooth Speaker,2,99.15,1.50,06/06/2023,Credit Card,Returned,-99.15
887,ORD11798,Rebecca Perez,FEMALE,2002-05-10,boyerautumn@example.com,001-987-779-9364x273,U.S.A,Hernandezhaven,East,95090.0,...,Gaming,Books,Fiction Novel,-1,66.81,0.15,2024-04-02,cc,Returned,-56.79

In [8]:
df.shape

(3110, 21)

In [9]:
df.columns

Index(['order_id', 'Name', 'gender', 'DOB', 'email', 'phone', 'country',
       'city', 'region', 'pincode', 'customer_segment', 'interest',
       'product_category', 'product_name', 'quantity', 'unit_price',
       'discount', 'order_date', 'payment_mode', 'order_status', 'revenue'],
      dtype='object')

In [10]:
df.index

RangeIndex(start=0, stop=3110, step=1)

In [11]:
df.dtypes

order_id             object
Name                 object
gender               object
DOB                  object
email                object
phone                object
country              object
city                 object
region               object
pincode             float64
customer_segment     object
interest             object
product_category     object
product_name         object
quantity              int64
unit_price          float64
discount            float64
order_date           object
payment_mode         object
order_status         object
revenue             float64
dtype: object

In [12]:
df.describe(include='object')

,order_id,Name,gender,DOB,email,phone,country,city,region,customer_segment,interest,product_category,product_name,order_date,payment_mode,order_status
count,3110,3110,2755,2847,2791,2633,2836,3110,3110,2342,2594,3110,3110,3110,3110,3110
unique,3000,2984,8,2704,2680,2542,10,2743,4,3,5,6,28,1915,13,10
top,ORD10682,katherine davis,Female,01-Sep-1985,paullopez@example.net,+1-666-490-5946,USA,New Michael,West,Corporate,Reading,Sports,Yoga Mat,2023-03-18,Debit Card,Cancelled
freq,3,3,373,3,4,3,311,6,829,809,559,534,158,6,263,341

In [13]:
df.describe(include='all')

,order_id,Name,gender,DOB,email,phone,country,city,region,pincode,...,interest,product_category,product_name,quantity,unit_price,discount,order_date,payment_mode,order_status,revenue
count,3110,3110,2755,2847,2791,2633,2836,3110,3110,2357.000000,...,2594,3110,3110,3110.000000,3110.000000,3110.000000,3110,3110,3110,2936.000000
unique,3000,2984,8,2704,2680,2542,10,2743,4,NaN,...,5,6,28,NaN,NaN,NaN,1915,13,10,NaN
top,ORD10682,katherine davis,Female,01-Sep-1985,paullopez@example.net,+1-666-490-5946,USA,New Michael,West,NaN,...,Reading,Sports,Yoga Mat,NaN,NaN,NaN,2023-03-18,Debit Card,Cancelled,NaN
freq,3,3,373,3,4,3,311,6,829,NaN,...,559,534,158,NaN,NaN,NaN,6,263,341,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49380.900721,...,NaN,NaN,NaN,1.743408,253.586839,0.227605,NaN,NaN,NaN,332.449991
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28896.767295,...,NaN,NaN,NaN,1.652823,144.327614,0.472513,NaN,NaN,NaN,525.389687
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,579.000000,...,NaN,NaN,NaN,-1.000000,5.030000,-0.100000,NaN,NaN,NaN,-1166.120000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24036.000000,...,NaN,NaN,NaN,1.000000,126.505000,0.000000,NaN,NaN,NaN,28.365000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48852.000000,...,NaN,NaN,NaN,1.000000,253.530000,0.100000,NaN,NaN,NaN,246.110000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74743.000000,...,NaN,NaN,NaN,2.000000,378.367500,0.150000,NaN,NaN,NaN,524.597500
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99945.000000,...,NaN,NaN,NaN,5.000000,499.940000,1.500000,NaN,NaN,NaN,2455.050000

In [14]:
#TRIM and FIX spacing

In [15]:
df["Name"] = df["Name"].str.strip()

In [17]:
# ---- 2. PROPER case fix (Find & Replace / PROPER equivalent) ----

In [18]:
df["Name"] = df["Name"].str.title()
df["payment_mode"] = df["payment_mode"].str.strip().str.title()
df["order_status"] = df["order_status"].str.strip().str.title()

In [ ]:
#Standardize gender
#notna : "Is this value NOT missing?" 
#.map() applies a function to every value in the column.
# gender_map.get(x, x) This is dictionary lookup.

In [21]:
gender_map = {
    "M":"Male","MALE":"Male", "Male": "Male", "m": "Male",
    "F": "Female", "FEMALE": "Female", "Female": "Female", "f": "Female"
}
df["gender"] = df["gender"].str.strip().str.upper().map(
    lambda x:gender_map.get(x,x) if pd.notna(x) else x )

In [22]:
# safer version using your original casing as fallback:
df["gender"] = df["gender"].replace({
    "M": "Male", "MALE": "Male", "m": "Male",
    "F": "Female", "FEMALE": "Female", "f": "Female"
})

In [23]:
# ---- 4. Flag bad data (Conditional Formatting equivalent) ----

In [24]:
df["flag_negative_qty"] = df["quantity"] < 0
df["flag_invalid_discount"] = df["quantity"] > 1
print("Negative quantity rows:", df["flag_negative_qty"].sum())
print("Invalid discount rows:", df["flag_invalid_discount"].sum())

Negative quantity rows: 402
Invalid discount rows: 1554

In [25]:
# ---- 5. Remove exact duplicate rows ----

In [26]:
len(df)

3110

In [28]:
before = len(df)
df = df.drop_duplicates()
print(f"Removed {before - len(df)} exact duplicates rows")

Removed 92 exact duplicates rows

In [29]:
# Flag duplicate order_id WITHOUT deleting (same as your COUNTIF formula)

In [33]:
df["duplicate_order_id"] = df["order_id"].duplicated(keep=False).map(
    {True: "duplicates", False: "unique"}
)
print(df["duplicate_order_id"].value_counts())

duplicate_order_id
unique        2982
duplicates      36
Name: count, dtype: int64

C:\Users\pushp\AppData\Local\Temp\ipykernel_18724\182506716.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["duplicate_order_id"] = df["order_id"].duplicated(keep=False).map(

In [34]:
# ---- 6. Pivot Tables (Revenue by Category, Revenue by Region) ----

In [35]:
pivot_category = df.pivot_table(values="revenue", index="product_category", aggfunc="sum").round(2)
pivot_region = df.pivot_table(values="revenue", index="region", aggfunc="sum").round(2)

In [36]:
print(pivot_category)
print(pivot_region)

                    revenue
product_category
Beauty            156112.75
Books             179496.37
Clothing          149389.92
Electronics       149446.03
Home & Kitchen    155378.65
Sports            157842.09
          revenue
region
East    218830.82
North   215870.32
South   234787.78
West    278176.89

In [37]:
# a. Rename columns for consistenc

In [38]:
df = df.rename(columns={
    "Name" : "customer_name",
    "gender" : "customer_gender",
    "DOB" : "date_of_birth"
})

In [39]:
# b. Drop irrelevant columns

In [41]:
df= df.drop(columns = ["interest"])

In [42]:
# c. Fix data types

In [44]:
df["date_of_birth"] = pd.to_datetime(df["date_of_birth"], errors="coerce")  # handles mixed formats
df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")

In [45]:
# d. Standardize categorical values

In [46]:
df["customer_name"] = df["customer_name"].str.strip().str.title()
df["customer_gender"] = df["customer_gender"].str.upper().map({
    "M": "Male", "MALE": "Male", "F": "Female", "FEMALE": "Female"
}).fillna(df["customer_gender"])
df["country"] = df["country"].str.strip().str.upper().replace({
    "INDIA": "India", "USA": "United States", "U.S.A": "United States",
    "UK": "United Kingdom"
})
df["payment_mode"] = df["payment_mode"].str.strip().str.title().replace({"Cc": "Credit Card", "Cod": "Cash On Delivery"})
df["order_status"] = df["order_status"].str.strip().str.title()

In [47]:
# e. Fix missing values using existing data

In [48]:
df["country"] = df["country"].fillna(df["country"].mode()[0])
mode_by_category = df.groupby("product_category")["customer_segment"].transform(lambda x: x.mode()[0] if not x.mode().empty else "Consumer")
df["customer_segment"] = df["customer_segment"].fillna(mode_by_category)

In [49]:
# f. Fix invalid business-logic values

In [50]:
# f. Fix invalid business-logic values
df = df[df["quantity"] > 0]                     # remove impossible negative quantities
df["discount"] = df["discount"].clip(0, 0.5)     # cap discount between 0% and 50%

In [51]:
# g. Recompute revenue instead of trusting missing/wrong values

In [52]:
df["revenue"] = (df["quantity"] * df["unit_price"] * (1 - df["discount"])).round(2)

In [53]:
# h. Remove exact duplicate rows

In [54]:
df = df.drop_duplicates()

In [55]:
# i. Handle duplicate order_ids (keep latest/highest revenue entry as business rule)

In [68]:
df = df.sort_values("revenue", ascending=False).drop_duplicates(subset="order_id", keep="first")

df.to_csv("ecommerce_sales_clean.csv", index=False)

In [69]:
df.duplicated().sum()

np.int64(0)

In [71]:
import os 
print(os.getcwd())

C:\Users\pushp\Contacts\Data_analyst_project

In [72]:
df.head()

,order_id,customer_name,customer_gender,date_of_birth,email,phone,country,city,region,pincode,...,unit_price,discount,order_date,payment_mode,order_status,revenue,flag_negative_qty,flag_invalid_discount,duplicates_order_id,duplicate_order_id
1805,ORD11132,William Huff,Male,1978-11-06,dunnjacob@example.net,(980)550-1417x165,United States,Port Donstad,East,52468.0,...,491.01,0.0,NaT,Net Banking,Delivered,2455.05,False,True,unique,unique
1279,ORD12216,Justin Sanchez,Male,NaT,brownlarry@example.com,719-272-9410x367,CANADA,Carrollbury,West,NaN,...,490.14,0.0,2023-04-23,Credit Card,Returned,2450.70,False,True,unique,unique
2060,ORD11419,Gina Jordan,Female,NaT,singletonnicole@example.net,(419)268-0450x5211,India,Port Robert,North,68509.0,...,488.14,0.0,NaT,Upi,Pending,2440.70,False,True,unique,unique
709,ORD10903,Shannon Sims,Female,1993-10-26,hudsonglen@example.net,001-949-387-4551x35872,United States,Adamsborough,East,3289.0,...,485.57,0.0,NaT,Debit Card,Returned,2427.85,False,True,unique,unique
2646,ORD12559,Pamela Aguilar,Female,NaT,diane11@example.com,426-414-2274x0451,United States,Melissahaven,East,74649.0,...,485.41,0.0,NaT,Debit Card,Returned,2427.05,False,True,unique,unique